### PR TITLE
fixed chinese translation

### PR DESCRIPTION
**Pull request by Eklos9z**

### CODE REVIEW

**Comment by Eklos9z** [comment]
Some of the function may not be well understood by me(like bitboard and umigame etc.), so I only make them seem to fit in the Chinese context.

**Comment by Eklos9z** [comment]
Sorry the usage translation is going to be delayed for a while because I've been so busy..

**Comment by Nyanyan** [comment]
Thank you very much for translation! I merged it.

You added your email address in chinese.json. If you don't mind, can I add your email address on the official website? something like: "中文翻译问题请联系:深红(Eklos): mail_address / For Chinese translation questions, please contact Eklos: mail_address"

Thank you for usage translation! Egaroucid 7.0.0 will be released in several months, and some features are planned to be added. Is it better to tell you the changes when I update usage page (in Japanese)?

**Comment by Eklos9z** [comment]
Thank you for your recognition. Considering that there might be better translations of some texts by others, I have included my contact information for communication. Regarding the translation work of usage, I am currently about 50% through v6.5.1. My plan is to complete the v6.5.1 first, and then make adjustments based on the soon-to-be-released (or by then already released) version 7.0.0.

**Pull request merged**
