### PR TITLE
Added Chinese translation

### PR DESCRIPTION
**Pull request by Eklos9z**

### CODE REVIEW

**Comment by Nyanyan** [comment]
@Eklos9z Thank you very much!
From next release (Egaroucid 6.5.0), Egaroucid can be used in Chinese.

I would like to add your name in Acknowledgements, Egaroucid's website. Is it OK? and how should I write your name? Egaroucid's website: https://www.egaroucid.nyanyan.dev/en/

image

**Comment by Nyanyan** [comment]
@Eklos9z If you have opening name list (like "diagonal opening" for ```f5f6```, "Tiger" for ```f5d6c3d3c4```), I would be pleased if you let me know. For now, although if you use Egaroucid in Chinese, the opening names are still in English.

**Comment by Eklos9z** [comment]
@Nyanyan Thank you for your recognition. My real name is ZhangHengge. Egaroucid is the best analysis software I have ever used. I am delighted to be able to contribute to it. Once the 6.5.0 version is released, I will attempt to popularize Egaroucid in the Chinese Othello Association. 
Regarding the “opening name list in Chinese” you mentioned, the Chinese Othello Association has not yet fully standardized the Chinese names for some openings. I will discuss a standard with relevant personnel from the Chinese Othello Association and submit new Pull requests.

**Comment by Nyanyan** [comment]
@Eklos9z Egaroucid 6.5.0 is now released. Thank you very much for your contribution!
You can download here: https://www.egaroucid.nyanyan.dev/en/download/

**Pull request merged**
